### PR TITLE
fix (lunchnlearn): prefix should be a non-captured group

### PR DESCRIPTION
**Pull request by cromwellryan**
When we switched to an alternation construct for our prefix in e2ffe22,
but used a captured group. Here we switch to a non-captured group.
:facepalm:

### CODE REVIEW

**Comment by bryanbraun** [comment]
This is better, but it doesn't address the other thing that broke in e2ffe226c2589fa787a948e2852a749b508c02c1... the issue where you can't forget `lunchnlearn` items.

I looked into it. It's because the backslash inside the JS string is inadvertently escaping characters and affecting the regular expression. Here's the fix:

```diff
  - robot.respond match_command("forget (\d+)"), (res) ->
  + robot.respond match_command("forget (\\d+)"), (res) ->
```

I'm pushing up a commit for this now. I'm good with your commit, so if mine looks good to you, I'd say lets merge this thing.

**Comment by cromwellryan** [comment]
oh! great find!

**Comment by cromwellryan** [comment]
Can I squash these before merging?

**Comment by bryanbraun** [comment]
Yeah, go for it!

**Comment by cromwellryan** [comment]
done. mergable

**Pull request merged**
